language: r
os:
  - linux
  - osx

before_install:
#  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y ghostscript; sudo apt-get install -y libmagick++-dev; sudo add-apt-repository -y ppa:cran/poppler; sudo apt-get update; sudo sudo apt-get install -y libpoppler-cpp-dev; sudo apt-get install -y libv8-dev ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; brew install v8 &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi

cache:
  packages: yes
sudo: false
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - if [ $TRAVIS_OS_NAME = osx ]; then brew tap homebrew/cask; brew cask install phantomJS; brew install imagemagick@6; brew install poppler; fi

script:
  - R CMD build .
  - R CMD INSTALL *tar.gz
  - if [ $TRAVIS_OS_NAME = osx ]; then R CMD check *tar.gz ; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then R CMD check *tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ] && [[ $TRAVIS_COMMIT_MESSAGE != *"[nobook]"* ]]; then ./_build.sh && ./_deploy.sh; fi

